language: java
branches:
  only:
    - master
  
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
  
services:
  - docker

before_script:
  - export JAVA_OPTS="-Xmx2048m"

install:
  - docker pull riveryang/redis:alpine
  - docker run -d --name redis_6379 -p 6379:6379 -e REDIS_PASSWORD=testpass riveryang/redis:alpine
  
script:
  - mvn test -Djava.net.preferIPv4Stack=true
  
notifications:
  email: false
  